name: MSVC Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: write

jobs:
  test_msvc:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Install MSVC
      uses: microsoft/setup-msbuild@v1.1

    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build and test MSVC
      shell: cmd
      run: |
        make test_msvc 