name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: write

jobs:
  test:
    timeout-minutes: 30  # Prevent jobs from running indefinitely
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc, clang]
        exclude:
          - os: windows-latest
            compiler: clang  # Skip Clang on Windows as it's not commonly available

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2  # For better version detection

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y valgrind gcc clang
      continue-on-error: false

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install gcc
      continue-on-error: false

    - name: Build and test (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        if [ "${{ matrix.compiler }}" == "gcc" ]; then
          CC=gcc make test_gcc
        else
          CC=clang make test_clang
        fi
      continue-on-error: true

    - name: Build and test (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        make test_gcc
      continue-on-error: true

    - name: Run Valgrind
      if: matrix.os == 'ubuntu-latest' && matrix.compiler == 'gcc'
      run: |
        make valgrind
      continue-on-error: true

    - name: Build examples
      run: |
        make examples
      continue-on-error: true 